SELECT
     -- idloja (VEM DO MIGRADOR CAMPO IDLOJA QUE DEVE SER SETADO NO INICIO DO MIGRADOR) -- smallint
    LEFT(PCB.CODIGO_BARRA, 30) AS ean,
    CASE
        WHEN PCB.CODIGO_BARRA IS NULL OR PCB.CODIGO_BARRA = '' THEN LEFT(CAST(p.ID AS VARCHAR(30)), 30)
        ELSE LEFT(PCB.CODIGO_BARRA, 30)
    END AS id,
    '*' AS idcor,
    CASE
        WHEN PCB.CODIGO_BARRA IS NULL OR PCB.CODIGO_BARRA = '' THEN LEFT(CAST(p.ID AS VARCHAR(20)), 20)
        ELSE LEFT(PCB.CODIGO_BARRA, 20)
    END AS idproduto,
    '*' AS idtamanho,
    CASE
        WHEN PCB.CODIGO_BARRA IS NULL OR PCB.CODIGO_BARRA = '' THEN LEFT(CAST(p.ID AS VARCHAR(20)), 20)
        ELSE LEFT(PCB.CODIGO_BARRA, 20)
    END AS referencia
FROM PRODUTO P
LEFT JOIN PRODUTO_CODIGO_BARRA PCB ON PCB.FK_PRODUTO = P.ID
